---
Name: silverstripe-file-credits
---
SilverStripe\Assets\File:
  extensions:
    - Ivoba\Extension\CreditsExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Ivoba\Extension\FileFormFactoryExtension
