---
Name: silverstripe-file-credits
---
SilverStripe\Assets\File:
  extensions:
    - Ivoba\SilverStripe\FileCredits\CreditsExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Ivoba\SilverStripe\FileCredits\FileFormFactoryExtension
