---
Name: silverstripe-file-credits
---
SilverStripe\Assets\File:
  extensions:
    - Ivoba\SilverStripe\CreditsExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Ivoba\SilverStripe\FileFormFactoryExtension
